### PR TITLE
Prepping to release 0.8.1

### PR DESCRIPTION
**Pull request by sosey**
Some final commits prepping for release

### CODE REVIEW

**Comment by sosey** [comment]
@larrybradley test please

**Comment by larrybradley** [comment]
Will do, thanks!

**Comment by larrybradley** [comment]
@sosey I tested this PR with @pllim's notebook and it works fine!

**Comment by larrybradley** [comment]
OSX  10.13.6
XQuartz 2.7.11

**Comment by sosey** [comment]
yah I'm running the same versions of OSX and XQuartz...still something messing up my env.... :(

**Comment by larrybradley** [comment]
I'm running `python 3.6.7`.  `tornado 5.1.1`, `ginga 2.7.2`

**Comment by sosey** [comment]
me too

**Comment by sosey** [comment]
@larrybradley wanna send me an env dump file?

**Comment by pllim** [comment]
Is Appveyor failure a blocker?

**Comment by sosey** [comment]
no

**Comment by larrybradley** [comment]
@pllim You could test in on windows. 😈

**Comment by pllim** [comment]
I did. See #151

**Pull request merged**
