### PR TITLE
windows install to ignore the xpa compile and ds9

### PR DESCRIPTION
**Pull request by sosey**
@pllim try this on your windows machine and verify that it works?

This should ignore the XPA compile for windows machines, the package import and connect should see that no xpa is available, and check if ginga *is* available and otherwise return a viewer error message.

So windows users should be able to install this and have access to ginga as the viewer instead of DS9.

### CODE REVIEW

**Comment by pllim** [comment]
Still has some error on import:

```python
In [1]: import imexam
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-98fd07d13683> in <module>()
----> 1 import imexam

...\imexam-0.6.3-py3.5.egg\imexam\__init__.py in ...
     13 if not _ASTROPY_SETUP_:
     14     # import high level functions into the imexam namespace
---> 15     from .util import list_active_ds9
     16     from .util import display_help, display_xpa_help
     17     from .util import set_logging

...\imexam-0.6.3-py3.5.egg\imexam\util.py in ...
      9 from astropy.io import fits
     10
---> 11 import xpa
     12 from .version import version as __version__
     13

ImportError: No module named 'xpa'
```

**Comment by pllim** [comment]
Ginga fails to connect in AAS workshop imexam demo notebook (see traceback) but Ginga works fine in its own demo notebook.

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-752aeef75109> in <module>()
----> 1 a=imexam.connect(viewer='ginga') #stars up a new tab with the ginga HTML5 viewer

...\imexam-0.6.3-py3.5.egg\imexam\connect.py in __init__(self, target, path, viewer, wait_time, quit_window, port)
    100             self.window = ginga(exam=self.exam,
    101                                 close_on_del=quit_window,
--> 102                                 port=port)
    103             # the viewer will track imexam with callbacks
    104             self._event_driven_exam = True

...\imexam-0.6.3-py3.5.egg\imexam\ginga_viewer.py in __init__(self, exam, close_on_del, logger, port, host, use_opencv)
    909 
    910         super(ginga, self).__init__(exam=exam, close_on_del=close_on_del,
--> 911                                     logger=logger, port=self._port)
    912 
    913     def _open_browser(self):

...\imexam-0.6.3-py3.5.egg\imexam\ginga_viewer.py in __init__(self, exam, close_on_del, logger, port)
    145 
    146         # create the viewer specific to this backend
--> 147         self._create_viewer(bind_prefs, viewer_prefs)
    148 
    149         # TODO: at some point, it might be better to simply add a custom

...\imexam-0.6.3-py3.5.egg\imexam\ginga_viewer.py in _create_viewer(self, bind_prefs, viewer_prefs, opencv, threads)
    932         self._threads = threads
    933         self._server = None
--> 934         self._start_server()
    935 
    936         self.ginga_view = self._server.get_viewer('Imexam Display')

...\imexam-0.6.3-py3.5.egg\imexam\ginga_viewer.py in _start_server(self)
    979             no_ioloop = True  # jupyter console and notebook
    980 
--> 981         self._server.start(no_ioloop=no_ioloop)
    982 
    983     def _shutdown(self):

c:\users\lim\documents\aas229_workshop\src\ginga\ginga\web\pgw\ipg.py in start(self, use_thread, no_ioloop)
    376                factory=self.factory, logger=self.logger)
    377 
--> 378         self.http_server = self.server.listen(self.port, self.host)
    379 
    380         if no_ioloop:

...\tornado\web.py in listen(self, port, address, **kwargs)
   1848         from tornado.httpserver import HTTPServer
   1849         server = HTTPServer(self, **kwargs)
-> 1850         server.listen(port, address)
   1851         return server
   1852 

...\tornado\tcpserver.py in listen(self, port, address)
    124         the `.IOLoop`.
    125         """
--> 126         sockets = bind_sockets(port, address=address)
    127         self.add_sockets(sockets)
    128 

...\tornado\netutil.py in bind_sockets(port, address, family, backlog, flags, reuse_port)
    192 
    193         sock.setblocking(0)
--> 194         sock.bind(sockaddr)
    195         bound_port = sock.getsockname()[1]
    196         sock.listen(backlog)

OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by sosey** [comment]
ahh, ports. I have a auto port detection that is selecting a port windows doesn't like. Specifying a port in the call to use ginga on connect works, for example:  
```viewer=imexam.connect(viewer='ginga',port=9647)```

**Comment by pllim** [comment]
When I specify the port as above, the whole demo notebook works fine! 👍

**Comment by pllim** [comment]
Fixes #84

**Pull request merged**
