### PR TITLE
Plot apphoto

### PR DESCRIPTION
**Pull request by yoachim**
So this is clearly way more than one should actually put in a single PR, but I was on a roll.

* Improved the initial guess values for centering on a Gaussian (the centering was failing badly on my ground-based images)
* Added a feature so the aperture photometry pops open a window to show where the aperture and sky annulus actually fall. Put in some extra parameters to control that plot. Maybe this should be spun off as a user registered function, but I like it.
* For most of the curve and surface fits, added a constant term to the fit with a 0-order polynomial via astropy compound model. It is usually inconsequential if the curve is slightly over-fit, but it fails badly when under-fit, thus the background term needs to be included and should probably be on by default. Still work to be done passing and printing the background values and adding options to turn it off.
* Removed duplicate code so now column_fit just calls line_fit+kwarg.
* Overhauled the unit tests to mostly remove mysterious magic values. Tests are better, but still very far from perfect (as usual).

### CODE REVIEW

**Comment by sosey** [comment]
Hey Peter, thanks for all the work and the PR! I'm a little crushed today and tomorrow but till look through this soon - cheers

**Comment by sosey** [comment]
@yoachim I'm going through your changes, in the mean time, will you work on updating the documentation for the new features that you added?  This is the price I'm extracting for such a large PR without making you split it up :wink:  I may have you squish some of the commits together still to clean up the history.

**Comment by yoachim** [comment]
Sure.  Might take me a little bit--looks like my sphinx install went a little wonky.

**Comment by sosey** [comment]
no worries, I just had fisticuffs with my editor settings and it put me behind a bit

**Comment by sosey** [comment]
The travis update I made barfed...will figure it out and push an update

**Comment by sosey** [comment]
merged with #128

**Pull request closed without merging**
