### PR TITLE
Check target before path

### PR DESCRIPTION
**Pull request by stscieisenhamer**
If a target is specified on connect(), there is,
technically, no reason to see if ds9 is in the path.
But maybe there is...?

### CODE REVIEW

**Comment by sosey** [comment]
the fix to show_xpa_commands is good!

The logic change to target.... technically in a world with users who know everything (I don't even include myself in this) then yes, if they supply a target name you shouldn't have to check the path cause you could assume they know they have ds9 installed, up and running. But it's possible that they don't realize there isn't DS9 on their machine, so none really exists to connect to, and they just give a random name.

However, I think the logic isn't really working for what I describe above.  If they specify target, and target doesn't exist because no ds9 process by that name is running, then imexam still creates the control object and doesn't say anything is wrong :O  I think we should put a nice user error statement in here to inform them there wasn't anything to connect to and to try again, or return the list of open ds9 windows for them to choose from  :)  Maybe something like this:
```
        if not target and not path:
            self._ds9_path = util.find_ds9()
            if self._ds9_path is None:
                raise OSError("Could not find ds9 executable on your path")
        else:
            self._ds9_path = path

        if not target:
            # Check to see if the user has chosen a preference first
            if 'XPA_METHOD' in os.environ:
                self._xpa_method = os.environ['XPA_METHOD'].lower()

            if 'inet' in self._xpa_method:
                self._xpa_name = self.run_inet_ds9()
                # xpa_name is the title of the window, the xpa can be
                # referenced with either the socket address or name
                # of the window

            elif 'local' in self._xpa_method:
                self._xpa_name, self._ds9_unix_name = self._run_unixonly_ds9()

            # tells xpa where to find sockets
            os.environ['XPA_METHOD'] = self._xpa_method

        else:
            # check to see if the target exists
            active = util.list_active_ds9()
            if target in list(active):
                self._xpa_name = target
            else:
                # see if they used a title and not the xpa_method
                # the title is the first item in the tuple for each key
                for window in active.values():
                    if target in window:
                        self._xpa_name = target
            if not self._xpa_name:
                print("\nDS9 target: {0:s} doesn't exist.\n{1}".format(target,
                                                                     active))
                raise ValueError("Please choose an existing target.")

```

Also, I changed the path and target parameters to empty string instead of None. They really should always be strings, so checking against string truth seems better than None, do you agree?

Wanna make those changes?

**Comment by stscieisenhamer** [comment]
👍 I'll make the mods this afternoon.

**Comment by stscieisenhamer** [comment]
@sosey just pinging if this is ready or not.

**Comment by sosey** [comment]
sorry - distracted.  Will you also update the changes file and the docs to go with this?

**Comment by sosey** [comment]
@stscieisenhamer if you don't have time for the docs update, make an issue linking back to this so so we don't forget to do it. But def make the changes update so it's current

**Comment by stscieisenhamer** [comment]
Will try to get to it this week, if not this week next week.

**Comment by stscieisenhamer** [comment]
I've update the changes.rst file and slightly modified the ds_viewer docstring. Otherwise, not clear any other doc updates were needed.

**Comment by sosey** [comment]
:shipit:

**Pull request merged**
