### PR TITLE
ginganb branch merge 

### PR DESCRIPTION
**Pull request by sosey**
- adding ginga HTML5 viewer
- removed the matplotlib and QT viewers in favor of the newer html5 one now available in Ginga
- grab ds9 window now available for notebook interaction
- matplotlib plots inside the notebook using the nbagg widgets

### CODE REVIEW

**Comment by sosey** [comment]
@mwcraig I'm still working on docs for this merge, but if you have time and want to give it a test run, checkout the ginganb branch and see how it runs for you in Jupyter? You should have access to the ginga html5 viewer as well as the ds9 viewer from there. Look at the short example notebooks in the example_notebooks directory... if you get any bugs report back? :)

**Comment by mwcraig** [comment]
@sosey -- thanks for the ping, will try to look at it this weekend.

**Comment by mwcraig** [comment]
Sorry, never did get to this, will let you know what I hit if anything when I get to it later this week.

**Comment by sosey** [comment]
@mwcraig  no rush. I merged over to the master so just pull that branch when you're ready :)

**Pull request merged**
