### PR TITLE
Add CODE_OF_CONDUCT.md to repo

### PR DESCRIPTION
**Pull request by pllim**
This is an automated addition of spacetelescope code of conduct that is copied from https://github.com/spacetelescope/stsci-package-template/. 

*If this is opened in error, please let @pllim know!*

### CODE REVIEW

**Comment by sosey** [comment]
@pllim  @eteq  not sure what to do with two codes of conduct since this package also reports the astropy Code...they're of the same ilk

**Comment by pllim** [comment]
xref astropy/package-template#295 and ejeschke/ginga#628 

IMHO anything under spacetelescope can just follow this one instead unless you want to move this under astropy org in the future.

**Comment by pllim** [comment]
P.s. As for what should all affiliated package really follow, regardless of host org, I think that's discussion for Coordination Committee.

**Comment by eteq** [comment]
I think I agree with @pllim on this.  Will discuss it with the CC, but my initial thinking is that this should get the ST one (i.e. merge this).  It'd be more of a concern if they were quite different, but they are very similar in wording.  One could argue that an astropy community member is agreeing to the Astropy CoC on some level, anyway, so it's sort of "by reference".  But this makes it clear that it's also this pkgs' code.

**Comment by sosey** [comment]
good, I just wanted a management stance on this stuff for STSci. Thanks.

**Pull request merged**
