### PR TITLE
Fix link target to point to the actual build rather than the badge

### PR DESCRIPTION
**Pull request by bsipocz**

### CODE REVIEW

**Comment by bsipocz** [comment]
Sure, either way. I've only noticed as trying to build the python3 conda packages for imexam in astropy/conda-channel-astropy#123 and it doesn't seem to work on windows while you have appveyor running and passing.

**Comment by pllim** [comment]
@sosey , I have access and looks like you do too. I can see you under "team".

**Comment by sosey** [comment]
hmm, do I need to approve teams access under my own account? I don't see it. @bsipocz I just did an install of imexam on my windows 10 machine and it installed and ran.

**Comment by bsipocz** [comment]
@sosey - Sadly appveyor is rather illogical with the team access. You need to log in with the team, and not with your own account. If you want to work with a repo under a different team, then log out and log in again with that team. Rather inconvenient, but I don't know any workarounds.

**Comment by pllim** [comment]
@sosey , when I go to Appveyor login page, I can choose which account to log in as. Try log out and see if you can then select the account?

**Comment by sosey** [comment]
right, that's kinda what I thought, but I don't have the team account name or password. If I look at teams under my own account I see a whole slew of teams and organizations, but I can only log in as myself or mike d.... I hadn't tried mikes before, but I just did and it let me go under my creds...so lemme see if I can do this now :)

**Comment by sosey** [comment]
Though we should probably just make a spacetelescope account and get off mike's

**Comment by bsipocz** [comment]
You don't need a passwd for a team, it will log you in via a github authentication even as part of the team.

**Comment by pllim** [comment]
@sosey , I agree.

**Comment by sosey** [comment]
okay - I changed my account settings to reflect spacetelescope and added ssb, @bsipocz will you update the link to: ```https://ci.appveyor.com/project/spacetelescope/imexam/branch/master ``` and I think we should be good. @pllim see if you can get into spacetelescope and we can discuss what the email address for the general account should be offline.

**Comment by bsipocz** [comment]
@sosey - Done

**Pull request merged**
