### PR TITLE
Issue fixes for upcoming release

### LINKED ISSUE #111: imexam() can't seem to handle drizzled products.
I can't seem to be able to use imexam() on drizzled products. It's a drizzled product where the 0th extension is the science frame and the 1st extension is a header table. Here's what the product looks like:

`In [25]: !fitsinfo f606w_long_median_drc_sci.fits
Filename: f606w_long_median_drc_sci.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU    1075   (6059, 6087)   float32   
  1  HDRTAB      BinTableHDU    631   20R x 311C   [9A, 3A, J, D, D, D, D, D, D, D, D, D, D, D, D, D, J, 3A, 9A, 7A, 18A, 4A, D, D, D, D, 3A, D, D, D, D, D, D, D, D, D, D, D, D, J, 8A, 23A, D, D, D, D, J, J, J, 8A, J, 23A, 9A, 19A, J, 4A, J, D, J, J, J, J, 23A, D, D, D, D, J, J, 3A, 23A, 4A, 4A, J, D, D, D, 3A, 1A, J, D, D, D, 13A, 3A, 4A, 4A, 12A, 12A, 23A, 8A, 23A, 10A, 10A, D, D, 3A, 3A, 23A, 4A, 8A, 7A, 23A, D, J, D, 6A, 9A, 8A, D, D, J, 4A, 18A, 3A, J, 5A, 7A, 3A, D, 13A, 8A, 4A, 3A, J, J, J, J, J, J, J, D, D, D, D, D, D, 23A, 1A, D, 23A, D, D, D, 3A, 23A, J, 1A, 3A, 6A, D, 3A, 6A, J, D, D, D, D, D, D, D, D, D, D, 23A, D, D, D, D, 3A, D, D, D, 1A, J, J, J, J, J, J, 23A, J, 5A, 7A, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, D, 13A, D, 24A, 23A, D, 1A, 1A, D, J, D, D, 1A, 1A, D, 4A, J, D, J, 8A, D, J, D, J, J, 23A, 23A, D, 8A, D, 29A, D, 3A, D, J, D, D, 4A, 5A, 7A, 1A, D, 3A, J, 1A, 1A, 1A, 1A, D, D, D, D, D, D, 4A, D, 4A, D, 4A, J, 4A, 3A, 1A, J, J, J, 1A, D, D, D, D, J, 3A, J, J, 6A, J, D, D, 11A, D, D, 3A, 8A, 1A, D, J, D, J, J, 5A, 4A, J, J, D, J, J, D, D, D, D, J, J, J, J, D, D, 8A, 8A, 3A, 3A]   

`

When I load using only the file name the header table gets displayed.

`In [26]: view.load_fits('f606w_long_median_drc_sci.fits')`

So I tried including the extension in the file name and that loaded the image, but when I try imexam() I get an error.

`In [27]: view.load_fits('f606w_long_median_drc_sci.fits[0]')

In [28]: view.imexam()

Press 'q' to quit

2	Make the next plot in a new window
a	Aperture sum, with radius region_size 
b	Return the 2D gauss fit center of the object
c	Return column plot
e	Return a contour plot in a region around the cursor
g	Return curve of growth plot
h	Return a histogram in the region around the cursor
j	1D [Gaussian1D default] line fit 
k	1D [Gaussian1D default] column fit
l	Return line plot
m	Square region stats, in [region_size],default is median
r	Return the radial profile plot
s	Save current figure to disk as [plot_name]
t	Make a fits image cutout using pointer location
w	Display a surface plot around the cursor location
x	Return x,y,value of pixel
y	Return x,y,value of pixel
Current image f606w_long_median_drc_sci.fits
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-28-5661250efd39> in <module>()
----> 1 view.imexam()

~/miniconda2/envs/devenv/lib/python3.6/site-packages/imexam/connect.py in imexam(self)
    150                 self._run_event_imexam()
    151             else:
--> 152                 self._run_imexam()
    153         else:
    154             warnings.warn("No valid image loaded in viewer")

~/miniconda2/envs/devenv/lib/python3.6/site-packages/imexam/connect.py in _run_imexam(self)
    222         if self.window.iscube():
    223             self._current_slice = self.window.get_slice_info()
--> 224         self.exam.set_data(self.window.get_data())
    225         current_key = keys[0]  # q is not in the list of keys
    226 

~/miniconda2/envs/devenv/lib/python3.6/site-packages/imexam/ds9_viewer.py in get_data(self)
   1042                             data = filedata[extname, extver].section[naxis]
   1043                         else:
-> 1044                             data = filedata[extname, extver].data
   1045                     return data
   1046                 else:

~/miniconda2/envs/devenv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in __getitem__(self, key)
    312         # instead
    313         return self._try_while_unread_hdus(super(HDUList, self).__getitem__,
--> 314                                            self._positive_index_of(key))
    315 
    316     def __contains__(self, item):

~/miniconda2/envs/devenv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in _positive_index_of(self, key)
    700         """
    701 
--> 702         index = self.index_of(key)
    703 
    704         if index >= 0:

~/miniconda2/envs/devenv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py in index_of(self, key)
    665                 '{} indices must be integers, extension names as strings, '
    666                 'or (extname, version) tuples; got {}'
--> 667                 ''.format(self.__class__.__name__, _key))
    668 
    669         _key = (_key.strip()).upper()

KeyError: 'HDUList indices must be integers, extension names as strings, or (extname, version) tuples; got None'

`

### LINKED ISSUE #112: Add a check to see if the extension being displayed is actually a binary table
`load_fits()` happily sends a fits binary table to ds9 without error, from either `imexam` or `ds9`, but nothing shows up obviously.  Return a message to the user asking for an explicit extension for display

This came up in #111 with display of an HLSP-type product with the following structure:
```
Filename: hlsp_frontier_hst_wfc3-60mas_abell2744_f105w_v0.5-20131101_drz.fits
No.    Name         Type      Cards   Dimensions   Format
  0  PRIMARY     PrimaryHDU     845   (5350, 6150)
  1  HDRTAB      BinTableHDU    557   4R x 274C  
```

### LINKED ISSUE #113: Fix extension references for MEF FITS image with image data in the PRIMARY extension
This was also brought to light by #111.

Think about the best defaults to use and how to pass explicit user information so that the correct extension is always referenced regardless of how the user loads the data into `ds9`. Also verify that these changes don't break anything in the `ginga` interface.

### LINKED ISSUE #132: Add a getting started section
Add a new sections for those not too familiar with python or with imexam that walks through some of the basics and gets them up and running with screenshots and simple examples. 

There's already some basic stuff here, but I think it can be made more explicit and helpful:
http://imexam.readthedocs.io/en/latest/imexam/description.html#usage

### LINKED ISSUE #134: imexam radial profiles - error in radius value on x-axis
http://imexam.readthedocs.io/en/latest/imexam/examples.html#example-2

Trying out Example 2, but find that the radial profile in python does not match the one from pyraf.  The radial profiles are helpful diagnostics for evaluating the quality of the PSFs.

Here is a comparison of the same star used in the example. 
imexam_ex2
The flux values match up nicely (see yellow lines), but the radius values seem to be offset from where they should be. Could there be an error in calculating the distance from the star centroid position?  For example, the second point from the top needs to move left in the python version.  I'm not sure if all radius values are off, or just a subset. 

Here is a second example, which shows the effect much more clearly.  

imexam_uvis_example

### PR DESCRIPTION
**Pull request by sosey**
These are some cumulative updates and issue fixes as I prepare the next release. Specifically they closes #134, closes #132, closes #113, closes #112, and closes #111  which include:

- radial profile plot centering changed slightly to use the max brightest pixel after gauss centering
- documentation updated and new simple walkthrough added
- MEF fits images with IMAGE arrays in the primary HDU should be detected correctly now
- now possible to give load_fits an in-memory fits object
- code cleanup and minor bug fixes
- addition of tests for the util package in association with the above fixes

### CODE REVIEW

**Comment by sosey** [comment]
@rjavila this PR should have the fixes for your drizzle images, give it a go and let me know if you run into any issues.

**Comment by rjavila** [comment]
@sosey How do I incorporate these changes to my environment? I uninstalled and re-installed. I now have version 0.8.1dev344 but I'm getting the same error as before so I don't think I did the upgrade properly.

**Comment by sosey** [comment]
@mackjenn I put updates to the radial profile code discussed  into this PR, if you install the branch this PR points to you can test them out.

**Comment by sosey** [comment]
pushing for upcoming hack, still need to update tests

**Pull request merged**
