### PR TITLE
Fixes for Ginga nb viewer

### PR DESCRIPTION
**Pull request by ejeschke**
Roll-up of many small fixes for the ginga nb viewer

- fixed typos that prevented viewer from initializing correctly, which
  affected keystroke operation
- fix for server--only one server is created per instance of running
    module--this prevents an "address already in use" error and is more
    efficient
- fix to allow multiple viewers to be created

### CODE REVIEW

**Comment by ejeschke** [comment]
@sosey, this fixes the immediate bugs with the notebook viewer.  Please test on your branch and lmk how it works for you.

**Comment by ejeschke** [comment]
I think I left the logger debugging defaulting to "debug" level (10)--I'll update this PR further, but go ahead and test anyway.

**Comment by sosey** [comment]
hah! I emailed you about 10 minutes ago saying that I had fixed about everything on my branch and for you to test it :) pull the ginganb branch and see if it 1) works for you 2) works with your changes? OR would you rather me start another pull request with that branch?

**Comment by sosey** [comment]
@ejeschke, took a quick look. We have a lot of overlap,  and I added some things and changed some names, I'll go through tomorrow and do the conflict merge and see where we're at. Thanks for the work!

**Comment by sosey** [comment]
@ejeschke I merged our changes and made a few more edits, the ginganb branch should be solidly working in the notebook now. I still need to work on the blocking from an ipython terminal once imexam() is called.

Question: I let people display numpy arrays into the viewer as well, but the default viewer is returning errors because there is no WCS to read from. Is there an easy way to shut off the WCS translations when a plain data array is loaded or is it better to define a bogus WCS for the image to avoid the error?

**Pull request merged**
